Document: ior
Title: Debian ior Manual
Author: <insert document author here>
Abstract: This manual describes what ior is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ior/ior.sgml.gz

Format: postscript
Files: /usr/share/doc/ior/ior.ps.gz

Format: text
Files: /usr/share/doc/ior/ior.text.gz

Format: HTML
Index: /usr/share/doc/ior/html/index.html
Files: /usr/share/doc/ior/html/*.html
